# Generated by Django 4.0.1 on 2023-06-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_categoryproduct_order_user_bot_token_user_cafe_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_color',
            field=models.CharField(default='#F5C332', max_length=255),
        ),
    ]
